# Generated by Django 5.1.7 on 2025-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leaguetable_match_matchavailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguetable',
            old_name='draw',
            new_name='draws',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='awayScore',
            new_name='away_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='awayTeam',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='homeScore',
            new_name='home_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='homeTeam',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='matchavailability',
            old_name='is_available',
            new_name='is_attending',
        ),
        migrations.AlterUniqueTogether(
            name='matchavailability',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sport',
        ),
        migrations.AddConstraint(
            model_name='matchavailability',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='unique_match_user_response'),
        ),
    ]
