# Generated by Django 5.1.7 on 2025-04-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_playergoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
